- hosts: all

  tasks:

    - name: Remove user key
      authorized_key: user="{{ user }}" key="{{ lookup('file', [path]) }}" state=absent
      sudo: yes


    - name: Remove user from remote machine
      user: name="{{ user }}" state=absent remove=yes
      sudo: yes