# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "host10" do |config|
      config.vm.box = "ubuntu/trusty64"
      config.vm.hostname = "host10.example.org"
      config.vm.network :private_network, ip: "192.168.33.110"
      config.vm.provider "virtualbox" do |v|
          v.name = "host10"
          v.customize ["modifyvm", :id, "--memory", 200]
      end
      
      config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/apache.yml"
      ansible.limit = "all"  ### <<-- workaround
      ansible.host_key_checking = false
      ansible.extra_vars = { ansible_ssh_user: 'vagrant',
			     ansible_connection: 'ssh',
                             ansible_ssh_args: '-o ForwardAgent=yes' }
      ansible.sudo = true
      end
    end

    config.vm.define "host20" do |config|
      config.vm.box = "ubuntu/trusty64"
      config.vm.hostname = "host20.example.org"
      config.vm.network :private_network, ip: "192.168.33.120"
      config.vm.provider "virtualbox" do |v|
          v.name = "host20"
          v.customize ["modifyvm", :id, "--memory", 200]
      end
      config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/apache.yml"
      ansible.limit = "all"  ### <<-- workaround
      ansible.host_key_checking = false
      ansible.extra_vars = { ansible_ssh_user: 'vagrant' , 
                             ansible_connection: 'ssh',
                             ansible_ssh_args: '-o ForwardAgent=yes' }
      ansible.sudo = true
      end
    end
    
    config.vm.define "host30" do |config|
      config.vm.box = "ubuntu/trusty64"
      config.vm.hostname = "host30.example.org"
      config.vm.network :private_network, ip: "192.168.33.130"
      config.vm.provider "virtualbox" do |v|
          v.name = "host30"
          v.customize ["modifyvm", :id, "--memory", 200]
      end
      config.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/haproxy.yml"
      ansible.limit = "all"  ### <<-- workaround
      ansible.host_key_checking = false
      ansible.extra_vars = { ansible_ssh_user: 'vagrant', 
                             ansible_connection: 'ssh',
                             ansible_ssh_args: '-o ForwardAgent=yes' }
      ansible.sudo = true
      end
    end

end
